// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrd9aKGEXAX2iGbUvn9pgD5NkAWj0JalE',
    appId: '1:519973694123:web:4b820a582fab796e8da5ee',
    messagingSenderId: '519973694123',
    projectId: 'postpartum-b21ff',
    authDomain: 'postpartum-b21ff.firebaseapp.com',
    storageBucket: 'postpartum-b21ff.firebasestorage.app',
    measurementId: 'G-B4SPLD1R5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA01CdetS-xhW6FTOEockU3ViIrqE3Gxw',
    appId: '1:519973694123:android:b155c23cf7f194238da5ee',
    messagingSenderId: '519973694123',
    projectId: 'postpartum-b21ff',
    storageBucket: 'postpartum-b21ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvt0xESXFJ6SJGLHJYwfUCuASbGnI1USc',
    appId: '1:519973694123:ios:dafc563a68ce51178da5ee',
    messagingSenderId: '519973694123',
    projectId: 'postpartum-b21ff',
    storageBucket: 'postpartum-b21ff.firebasestorage.app',
    iosBundleId: 'com.example.postpartumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvt0xESXFJ6SJGLHJYwfUCuASbGnI1USc',
    appId: '1:519973694123:ios:dafc563a68ce51178da5ee',
    messagingSenderId: '519973694123',
    projectId: 'postpartum-b21ff',
    storageBucket: 'postpartum-b21ff.firebasestorage.app',
    iosBundleId: 'com.example.postpartumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrd9aKGEXAX2iGbUvn9pgD5NkAWj0JalE',
    appId: '1:519973694123:web:ecb33b370e599da18da5ee',
    messagingSenderId: '519973694123',
    projectId: 'postpartum-b21ff',
    authDomain: 'postpartum-b21ff.firebaseapp.com',
    storageBucket: 'postpartum-b21ff.firebasestorage.app',
    measurementId: 'G-VYJTL5JQSC',
  );
}
